typography_spectrum: 0.50343
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.47599
analytics:
  google: null
  facebook: null
  twitter: null
name: de riethorst
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: De Riethorst
description: briljante plek in Friesland
purpose: []
